### ISSUE TITLE
/dokumente/transferspeicher'(post).responses.201.UploadWithUrl.requestBody is not of type `string`

### ISSUE THREAD

**Issue by jhackel-hypo** [europace/unterlagen-api#49]
## Fehlerbeschreibung

Die API kann nicht mit einem validierenden [OpenAPI-Generator](https://github.com/OpenAPITools/openapi-generator) übersetzt werden. Die Übersetzung bricht mit folgender Fehlermeldung ab:

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors: 
	-attribute paths.'/dokumente/transferspeicher'(post).responses.201.UploadWithUrl.requestBody is not of type `string`
```

Das passiert mit der aktuellsten stabilen Version 4.3.1.

## Hinweise
Ich kenne mich nicht so gut mit OpenAPI aus, aber meiner Meinung nach darf hier keine Property `url` definiert werden:

https://github.com/europace/unterlagen-api/blob/88c9fe53753ef6976c88ad146690e994456cf9b2/swagger.yaml#L130-L134

Laut OpenAPI-Spec darf das Feld `requestBody` eines [Link Objects](https://spec.openapis.org/oas/v3.0.3#linkObject) nur einen festen Wert oder eine [Runtime Expression](https://spec.openapis.org/oas/v3.0.3#runtimeExpression) enthalten. Ihr versucht aber einen strukturierten Body zu definieren.

**Comment by jhackel-hypo** [comment]
Meiner Meinung nach muss der Paramter `url` unter `parameters` definiert werden:

```json
links:
    UploadWithUrl:
        operationId: uploadDokument
        parameters:
            url: '$response.body#/downloadUrl'
```

**Comment by a4blue** [comment]
Der Swagger Validator wirft diesen Fehler auch:
Request:
https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fraw.githubusercontent.com%2Feuropace%2Funterlagen-api%2Fmaster%2Fswagger.yaml
Response:
```json
{"messages":
["attribute paths.'/dokumente/transferspeicher'(post).responses.201.UploadWithUrl.requestBody is not of type `string`"]
}
```

**Comment by YunaBraska** [comment]
Hi, im branch #55 findet ihr eine `https://raw.githubusercontent.com/europace/unterlagen-api/fix/0/swagger/uploadDokument/swagger.yaml` bitte validiert ob dies euer problem löst.

**Comment by jhackel-hypo** [comment]
> Hi, im branch #55 findet ihr eine `https://raw.githubusercontent.com/europace/unterlagen-api/fix/0/swagger/uploadDokument/swagger.yaml` bitte validiert ob dies euer problem löst.

Funktioniert jetzt! :+1: 

Getestet mit Gradle-Plugin `org.hidetake.swagger.generator:2.18.2` und OpenAPI-Generator `org.openapitools:openapi-generator-cli:5.1.1`.
